//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Team1Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITeam1ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class Team1ParserBaseListener : ITeam1ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_rule([NotNull] Team1Parser.Start_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_rule([NotNull] Team1Parser.Start_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrucciones([NotNull] Team1Parser.InstruccionesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrucciones([NotNull] Team1Parser.InstruccionesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] Team1Parser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] Team1Parser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl([NotNull] Team1Parser.Var_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl([NotNull] Team1Parser.Var_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.input_datos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_datos([NotNull] Team1Parser.Input_datosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.input_datos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_datos([NotNull] Team1Parser.Input_datosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.input_usuario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_usuario([NotNull] Team1Parser.Input_usuarioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.input_usuario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_usuario([NotNull] Team1Parser.Input_usuarioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.asignacion_suma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsignacion_suma([NotNull] Team1Parser.Asignacion_sumaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.asignacion_suma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsignacion_suma([NotNull] Team1Parser.Asignacion_sumaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.ciclo_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCiclo_loop([NotNull] Team1Parser.Ciclo_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.ciclo_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCiclo_loop([NotNull] Team1Parser.Ciclo_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.check_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCheck_block([NotNull] Team1Parser.Check_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.check_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCheck_block([NotNull] Team1Parser.Check_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.elseif_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif_bloque([NotNull] Team1Parser.Elseif_bloqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.elseif_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif_bloque([NotNull] Team1Parser.Elseif_bloqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.else_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_bloque([NotNull] Team1Parser.Else_bloqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.else_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_bloque([NotNull] Team1Parser.Else_bloqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicion([NotNull] Team1Parser.CondicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicion([NotNull] Team1Parser.CondicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.or_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_cond([NotNull] Team1Parser.Or_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.or_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_cond([NotNull] Team1Parser.Or_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.and_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_cond([NotNull] Team1Parser.And_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.and_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_cond([NotNull] Team1Parser.And_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.not_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_cond([NotNull] Team1Parser.Not_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.not_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_cond([NotNull] Team1Parser.Not_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparacion([NotNull] Team1Parser.ComparacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparacion([NotNull] Team1Parser.ComparacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] Team1Parser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] Team1Parser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.numero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumero([NotNull] Team1Parser.NumeroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.numero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumero([NotNull] Team1Parser.NumeroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.valor_salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValor_salida([NotNull] Team1Parser.Valor_salidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.valor_salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValor_salida([NotNull] Team1Parser.Valor_salidaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSalida([NotNull] Team1Parser.SalidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSalida([NotNull] Team1Parser.SalidaContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
