//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Team1Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Team1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ITeam1ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart_rule([NotNull] Team1Parser.Start_ruleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart_rule([NotNull] Team1Parser.Start_ruleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstrucciones([NotNull] Team1Parser.InstruccionesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstrucciones([NotNull] Team1Parser.InstruccionesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] Team1Parser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] Team1Parser.InstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl([NotNull] Team1Parser.Var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl([NotNull] Team1Parser.Var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.input_datos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_datos([NotNull] Team1Parser.Input_datosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.input_datos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_datos([NotNull] Team1Parser.Input_datosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.input_usuario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_usuario([NotNull] Team1Parser.Input_usuarioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.input_usuario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_usuario([NotNull] Team1Parser.Input_usuarioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.asignacion_suma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsignacion_suma([NotNull] Team1Parser.Asignacion_sumaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.asignacion_suma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsignacion_suma([NotNull] Team1Parser.Asignacion_sumaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.ciclo_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCiclo_loop([NotNull] Team1Parser.Ciclo_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.ciclo_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCiclo_loop([NotNull] Team1Parser.Ciclo_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.check_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCheck_block([NotNull] Team1Parser.Check_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.check_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCheck_block([NotNull] Team1Parser.Check_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.elseif_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseif_bloque([NotNull] Team1Parser.Elseif_bloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.elseif_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseif_bloque([NotNull] Team1Parser.Elseif_bloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.else_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_bloque([NotNull] Team1Parser.Else_bloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.else_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_bloque([NotNull] Team1Parser.Else_bloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicion([NotNull] Team1Parser.CondicionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicion([NotNull] Team1Parser.CondicionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.or_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_cond([NotNull] Team1Parser.Or_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.or_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_cond([NotNull] Team1Parser.Or_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.and_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_cond([NotNull] Team1Parser.And_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.and_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_cond([NotNull] Team1Parser.And_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.not_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_cond([NotNull] Team1Parser.Not_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.not_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_cond([NotNull] Team1Parser.Not_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparacion([NotNull] Team1Parser.ComparacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparacion([NotNull] Team1Parser.ComparacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] Team1Parser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] Team1Parser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.numero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumero([NotNull] Team1Parser.NumeroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.numero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumero([NotNull] Team1Parser.NumeroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.valor_salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValor_salida([NotNull] Team1Parser.Valor_salidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.valor_salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValor_salida([NotNull] Team1Parser.Valor_salidaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Team1Parser.salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSalida([NotNull] Team1Parser.SalidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Team1Parser.salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSalida([NotNull] Team1Parser.SalidaContext context);
}
